-- Create test tables with superclass fields

CREATE TABLE EMPLOYEE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100),
    DEPARTMENT VARCHAR(50),
    SALARY DECIMAL(10, 2),
    -- Superclass fields
    CREATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP,
    DELETED BOOLEAN DEFAULT FALSE
);

CREATE TABLE DEPARTMENT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    DEPT_NAME VARCHAR(100) NOT NULL,
    LOCATION VARCHAR(100),
    -- Superclass fields
    CREATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP,
    DELETED BOOLEAN DEFAULT FALSE
);

CREATE TABLE PROJECT (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PROJECT_NAME VARCHAR(200) NOT NULL,
    START_DATE DATE,
    END_DATE DATE,
    BUDGET DECIMAL(15, 2),
    -- Superclass fields
    CREATED_BY VARCHAR(50),
    CREATED_AT TIMESTAMP,
    UPDATED_BY VARCHAR(50),
    UPDATED_AT TIMESTAMP,
    DELETED BOOLEAN DEFAULT FALSE
);

-- Insert sample data
INSERT INTO EMPLOYEE (NAME, EMAIL, DEPARTMENT, SALARY, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, DELETED)
VALUES ('John Doe', 'john@example.com', 'Engineering', 75000.00, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, FALSE);

INSERT INTO DEPARTMENT (DEPT_NAME, LOCATION, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, DELETED)
VALUES ('Engineering', 'Building A', 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, FALSE);

INSERT INTO PROJECT (PROJECT_NAME, START_DATE, END_DATE, BUDGET, CREATED_BY, CREATED_AT, UPDATED_BY, UPDATED_AT, DELETED)
VALUES ('Project Alpha', '2026-01-01', '2026-12-31', 500000.00, 'admin', CURRENT_TIMESTAMP, 'admin', CURRENT_TIMESTAMP, FALSE);

