-- Initialization script for template test database
-- This creates sample tables to test custom template generation

-- Department table with various column types
CREATE TABLE department (
    dept_id INTEGER NOT NULL PRIMARY KEY,
    dept_name VARCHAR(100) NOT NULL,
    location VARCHAR(200),
    created_date DATE DEFAULT CURRENT_DATE,
    active BOOLEAN DEFAULT TRUE,
    description CLOB,
    budget DECIMAL(15,2)
);

-- Employee table with relationships and versioning
CREATE TABLE employee (
    emp_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE,
    dept_id INTEGER,
    hire_date DATE NOT NULL,
    salary DECIMAL(10,2),
    version INTEGER NOT NULL DEFAULT 1,
    notes TEXT,
    CONSTRAINT fk_dept FOREIGN KEY (dept_id) REFERENCES department(dept_id)
);

-- Product table to test different data types
CREATE TABLE product (
    product_code VARCHAR(20) NOT NULL PRIMARY KEY,
    product_name VARCHAR(200) NOT NULL,
    category VARCHAR(50),
    price DECIMAL(10,2) NOT NULL,
    stock_quantity INTEGER DEFAULT 0,
    manufacturing_date DATE,
    expiry_date DATE,
    is_available BOOLEAN DEFAULT TRUE,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    product_info CLOB,
    tags VARCHAR(500)
);

-- Add table comments for testing
COMMENT ON TABLE department IS 'Department master table';
COMMENT ON TABLE employee IS 'Employee information table';
COMMENT ON TABLE product IS 'Product catalog table';

-- Add column comments
COMMENT ON COLUMN department.dept_id IS 'Department unique identifier';
COMMENT ON COLUMN department.dept_name IS 'Department name';
COMMENT ON COLUMN employee.emp_id IS 'Employee ID (auto-generated)';
COMMENT ON COLUMN employee.version IS 'Version for optimistic locking';
COMMENT ON COLUMN product.product_code IS 'Product SKU code';