<#-- Custom lib.ftl with shared utilities -->
<#assign copyright>
/*
 * This file was generated by Doma-CodeGen with custom templates.
 * Template Test Project
 * Generated at: ${.now?string("yyyy-MM-dd HH:mm:ss")}
 */
</#assign>

<#assign author = "Custom Template Generator">

<#-- Helper function to format property names -->
<#function toSnakeCase camelCase>
    <#return camelCase?replace("([a-z])([A-Z])", "$1_$2", "r")?lower_case>
</#function>

<#-- Helper to check if a type is a primitive wrapper -->
<#function isPrimitiveWrapper className>
    <#local wrappers = ["Integer", "Long", "Double", "Float", "Boolean", "Short", "Byte", "Character"]>
    <#return wrappers?seq_contains(className)>
</#function>