name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    outputs:
      release_ref: ${{ steps.release-ref.outputs.release_ref }}
 
    steps:
      - name: Assign input version
        if: inputs.version != ''
        run: echo "RELEASE_VERSION=${{ inputs.version }}" >> $GITHUB_ENV

      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        if: inputs.version == ''
        id: candidate-version
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          result-encoding: string
          script: |
            const list = await github.rest.repos.listReleases({
              owner: "domaframework",
              repo: "doma-codegen-plugin",
            });
            console.log(list)
            let version = list.data[0].name
            return version.startsWith("v") ? version.substring(1) : version

      - name: Assign candidate version
        if: inputs.version == ''
        run: echo "RELEASE_VERSION=${{ steps.candidate-version.outputs.result }}" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Release ${{ env.RELEASE_VERSION }}
        run: |
          java -version
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          ./gradlew release -Prelease.releaseVersion=${{ env.RELEASE_VERSION }}

      - name: Assign release ref
        id: release-ref
        run: echo "release_ref=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT

      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: build
          path: ./**/build/reports

  verify-and-publish:
    name: Verify and Publish
    needs: release
    uses: ./.github/workflows/ci.yml
    with:
      ref: ${{ needs.release.outputs.release_ref }}
      publish: true
    secrets: inherit
